### ISSUE TITLE
Depricated Discord.js function

### ISSUE THREAD

**Issue by BannerBomb** [gavwin/discord-bot-in-every-lib#1]
Just to say in the file [here](https://github.com/gavwin/discord-bot-in-every-lib/blob/master/JavaScript/discordjs.js) where it says **msg.channel.sendMessage()** that is deprecated in discord.js now it should be **msg.channel.send()**

**Comment by gavwin** [comment]
[fixed](https://github.com/gavwin/discord-bot-in-every-lib/blob/master/JavaScript/discordjs.js)
